name: open_project_time_tracker
description: A new Flutter project.
publish_to: "none"

version: 1.9.2+61

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.8
  countly_flutter: 25.4.4
  provider: 6.1.2
  bloc: 8.1.4
  flutter_bloc: 8.1.6
  freezed_annotation: 2.4.4
  http: 1.2.2
  flutter_web_auth_2: ^4.0.1
  intl: 0.20.2
  injectable: 2.4.4
  iso_duration_parser: 1.1.1
  get_it: 7.7.0
  json_annotation: 4.9.0
  flutter_secure_storage: 9.2.2
  rxdart: 0.28.0
  shared_preferences: 2.3.2
  percent_indicator: 4.2.3
  retrofit: 4.2.0
  dio: 5.6.0
  json_serializable: 6.8.0
  fl_chart: 0.68.0
  flutter_dotenv: 5.1.0
  flutter_local_notifications: 19.4.0
  timezone: 0.10.1
  msh_checkbox: 2.0.1
  shimmer: 3.0.0
  url_launcher: 6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.13.1
  retrofit_generator: 8.1.0
  freezed: 2.5.2
  injectable_generator: 2.6.2
  build_runner: 2.4.12
  flutter_lints: 6.0.0

# to set icons run
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  image_path: "assets/logo_filled_background.png"
  adaptive_icon_background: #FFFFFF
  adaptive_icon_foreground: "assets/logo_filled_background.png"

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/microsoft_calendar.png
    - .env
