name: Deploy iOS

on: workflow_dispatch

jobs:
  deploy-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: ios

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.8"
          channel: "stable"

      - name: Setup project
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Create env file
        run: |
          touch .env
          echo "GRAPH_API_CLIENT_ID=${{ secrets.GRAPH_API_CLIENT_ID }}" > .env
          echo "COUNTLY_APP_KEY=${{ secrets.COUNTLY_APP_KEY }}" >> .env
          echo "COUNTLY_URL=${{ secrets.COUNTLY_URL }}" >> .env
          echo "PRIVACY_POLICY_URL=${{ secrets.PRIVACY_POLICY_URL }}" >> .env

      - name: Install Ruby dependencies
        run: |
          cd ios
          bundle install

      - name: Prepare match credentials
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
        run: |
          if [ -n "$PAT_TOKEN" ]; then
            echo "::add-mask::$PAT_TOKEN"
            echo "MATCH_GIT_BASIC_AUTHORIZATION=$(printf "x-access-token:%s" "$PAT_TOKEN" | base64)" >> $GITHUB_ENV
          fi
          if [ -n "$MATCH_GIT_URL" ]; then
            echo "MATCH_GIT_URL=$MATCH_GIT_URL" >> $GITHUB_ENV
          else
            echo "MATCH_GIT_URL=https://github.com/VonRehberg/ios-certificates.git" >> $GITHUB_ENV
          fi

      - name: Build, sign and deploy
        env:
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_KEY_CONTENT }}
          KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ env.MATCH_GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ env.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_READONLY: ${{ vars.MATCH_READONLY }}
          IOS_APP_IDENTIFIER: ${{ secrets.IOS_APP_IDENTIFIER }}
          IOS_WIDGET_IDENTIFIER: ${{ secrets.IOS_WIDGET_IDENTIFIER }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
        run: |
          cd ios
          bundle exec fastlane build_and_deploy
